
# NumPy

numpy's main object is called an ndarray.  It is:

1. multidimensional
2. homogenous
3. array

Meaning, it is a table elements, usually numbers.  All elements are the same type.  Elements are accessed by a tuple of positive integers.

Dimensions are called axes.
The number of axes is the rank.

Book ref: https://learning.oreilly.com/library/view/python-data-science/9781491912126/ch02.html#broadcasting-in-practice

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr)

[1 2 3 4 5 6 7 8 9]


In [2]:
#no of dimension
np.ndim(arr)

1

In [3]:
# a = np.array(np.arange(15).reshape(3,5))
# print(a)

arr2 = np.array(np.arange(100).reshape(10,10))

print(arr2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
np.ndim(arr2)

2

In [5]:
arr2.shape

(10, 10)

In [6]:
arr2.ndim

2

In [7]:
arr2.dtype.name

'int64'

In [8]:
#size in bytes
arr2.itemsize

8

In [11]:
arr2.size

100

In [12]:
type(arr2)

numpy.ndarray

We have three ways to access "row" 1 of a

In [14]:
arr2[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr2[1,]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [1]:
arr2[1,:]

NameError: name 'arr2' is not defined

In [21]:
arr2[0,2:6]

array([2, 3, 4, 5])

To get column in any position:

In [24]:
arr2[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
arr2[:,9]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

To get a single element in "row" 0, "column" 2

In [27]:
arr2[0,2]

np.int64(2)

Creating and modifying an array:

In [33]:
arr3 = np.array([1,2,3,4,5])
arr3.dtype.name


'int64'

In [34]:
arr4 = np.array([1.5,2.3,3.6,4.8,5.0])
arr4.dtype.name

'float64'

Let's change one element of c:

In [36]:
arr3[2] = 8.8
arr3.dtype.name

'int64'

Note that the type didn't change

In [39]:
print(arr3)

[1 2 8 4 5]


The value was added but was converted to an int64 - be careful - type matters!

NumPy interprets a sequence of sequences as a 2D array.  A sequence of sequence of sequences as a 3D array - etc

In [43]:
arr5 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr5)
arr5.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

Remember c from above?  Here is how we can change from integers to floats:

In [45]:
print(arr4)
arr4 = np.array(arr4,dtype=float)
arr4[1] = 8.8
print(arr4)
arr4.dtype.name

[1.5 8.8 3.6 4.8 5. ]
[1.5 8.8 3.6 4.8 5. ]


'float64'

Suppose you want to fill an array with all zeros or 1 (this is a suprisingly common task in data science)

In [47]:
arr6 = np.zeros((3,4))
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [50]:
arr7 = np.zeros((4,5),dtype = np.int64)
print(arr7)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [51]:
arr7 = np.ones((3,3,3),dtype = np.int16)
print(arr7)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


Similar to the range funtion in the standard python library NumPy has arange.  It allows us to create an array containing a range of numbers evenly spaced.

In [52]:
arr8 = np.arange(0,100,10) #start, stop, step
print(arr8)

[ 0 10 20 30 40 50 60 70 80 90]


In [53]:
arr9 = np.arange(0.1,0.9,0.1)
print(arr9)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]


Exercise 1: Create a 4X2 integer array and Prints its attributes
* The shape of an array.
* Array dimensions.
* The Length of each element of the array in bytes.

Save your code and output as a screenshot named numpy1.jpeg




Exercise 2: Following is the given numpy array return array of odd rows and even columns

In [ ]:

sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print("Printing Input Array")
print(sampleArray)



Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
