# NumPy

numpy's main object is called an ndarray.  It is:

1. multidimensional
2. homogenous
3. array

Meaning, it is a table elements, usually numbers.  All elements are the same type.  Elements are accessed by a tuple of positive integers.

Dimensions are called axes.
The number of axes is the rank.

Book ref: https://learning.oreilly.com/library/view/python-data-science/9781491912126/ch02.html#broadcasting-in-practice

In [3]:
import numpy as np

arr_1 = np.array([1,2,3,4,5,6,7,8,9])

print(arr_1)

[1 2 3 4 5 6 7 8 9]


In [5]:
np.ndim(arr_1)

1

In [7]:
arr_2 = np.arange(100).reshape(10,10)
print(arr_2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [8]:
np.ndim(arr_2)

2

In [9]:
arr_2.shape

(10, 10)

In [10]:
arr_2.ndim

2

In [11]:
arr_2.dtype.name

'int64'

In [12]:
#size in bites
arr_2.itemsize

8

In [13]:
arr_2.size

100

In [14]:
type(arr_2)

numpy.ndarray

We have three ways to access "row" 1 of a

In [16]:
arr_2[5]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [18]:
arr_2[5,]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [19]:
arr_2[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

To get column in postiion 2:

In [20]:
arr_2[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

To get a single element in "row" 0, "column" 2

In [21]:
arr_2[2,5]

np.int64(25)

Creating and modifying an array:

In [23]:
arr_3 = np.array([2,3,4])
arr_3.dtype.name

'int64'

In [25]:
arr_4 = np.array([1.1,2.2,3.3,4.4])
arr_4.dtype.name

'float64'

Let's change one element of c:

In [27]:
arr_3[2] = 4.4
arr_3.dtype.name

'int64'

Note that the type didn't change

In [28]:
print(arr_3)

[2 3 4]


The value was added but was converted to an int64 - be careful - type matters!

NumPy interprets a sequence of sequences as a 2D array.  A sequence of sequence of sequences as a 3D array - etc

In [29]:
arr_5 = np.array([[1,2,3], [4,5,6]])
print(arr_5)

[[1 2 3]
 [4 5 6]]


Remember c from above?  Here is how we can change from integers to floats:

In [32]:
print(arr_3)
arr_3 = np.array(arr_3,dtype=np.float64)
print(arr_3)

[2. 3. 4.]
[2. 3. 4.]


Suppose you want to fill an array with all zeros or 1 (this is a suprisingly common task in data science)

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
np.ones((2,3,4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

Similar to the range funtion in the standard python library NumPy has arange.  It allows us to create an array containing a range of numbers evenly spaced.

In [25]:
np.arange(10,30,5) #start, stop, step

array([10, 15, 20, 25])

In [26]:
np.arange(0.3, 1.5, 0.1)

array([0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4])

Exercise 1: Create a 4X2 integer array and Prints its attributes
* The shape of an array.
* Array dimensions.
* The Length of each element of the array in bytes.

Save your code and output as a screenshot named numpy1.jpeg




In [27]:
# Cell for coding exercise 1
firstArray = np.empty([4,2], dtype = np.uint16)
print("Printing Array")
print(firstArray)

print("Printing numpy array Attributes")
print("1> Array Shape is: ", firstArray.shape)
print("2>. Array dimensions are ", firstArray.ndim)
print("3>. Length of each element of array in bytes is ", firstArray.itemsize)

Printing Array
[[    0     0]
 [    0 49152]
 [32767 32696]
 [31247     0]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


Exercise 2: Following is the given numpy array return array of odd rows and even columns

In [28]:

sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of odd rows and even columns")
newArray = sampleArray[1::2, 0::2]
print(newArray)

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

 Printing array of odd rows and even columns
[[15 21]
 [39 45]]
